language: node_js
node_js:
  - 18

branches:
  only:
    - master

install:
  - "npm install"

script:
  - "npm run lint"
  - "npm run test:coverage"

before_install:
  - pip install --user codecov

after_success:
  - codecov
